baseURL = "https://example.com/"
languageCode = "en-US"
title = "Christopher Navas"
theme = "hugo-resume"

[params]
    firstName = "Christopher"
    lastName = "Navas"
    address = "Paris, France"
    phone = "+33637812593"
    contactNote = "Développeur web"
    profileImage = "img/me.jpg"
    email = "christo.navas@hotmail.fr"
    description = "Développeur web / Étudiant en 3eme année à la Web School Factory"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/christopher-navas/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/christophernavas/"

[params.google.analytics]
    trackerID = "XX-123446-01"
